language: c

sudo: false

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.2
    - LUA=lua5.3

branches:
  only:
    - master

before_install:
  - sudo apt-get install -y libsqlite3-0 libsqlite3-dev
  - source .travis/setenv_lua.sh
  - luarocks install luaunit

install:
  - luarocks make CFLAGS="-O2 -fPIC -std=c99"

script:
  - lua test.lua

notifications:
  email:
    on_success: change
    on_failure: always
