name: ci
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        luaVersion: ["5.2", "5.3"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - uses: leafo/gh-actions-luarocks@v4.0.0
      - name: build
        run: |
          luarocks install luaunit
          luarocks make
      - name: test
        run: |
          lua test.lua -v
